version: "3.8"

services:
  ts-node-express:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/usr/src/app/src
      - ./nodemon.json:/usr/src/app/nodemon.json
    ports:
      - 4000:4000
      - 9229:9229
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
      SERVER_PORT: 4000
    command: npm run dev

  postgres:
    image: postgres
    restart: always
    volumes:
      - testdb-postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb

volumes:
  testdb-postgres-data:
